# Docker Compose configuration for local PostgreSQL database
services:
  postgres:
    image: postgres:16
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: yaqoob
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: Sketch.io
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
