FROM node:18-alpine

WORKDIR /usr/src/app

ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_WS_URL
ARG DATABASE_URL

ENV NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
ENV NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
ENV DATABASE_URL=${DATABASE_URL}

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./apps/cosketch-frontend ./apps/cosketch-frontend

RUN npm install
RUN npm run db:generate
RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "start:frontend"]
