FROM oven/bun:1

WORKDIR /app

# Copy root workspace metadata first
COPY package.json bun.lock* ./

# Copy only the workspaces required by backend
COPY packages ./packages
COPY apps/cosketch-backend ./apps/cosketch-backend


RUN bun install
WORKDIR /app/packages/database
RUN bunx prisma generate

RUN bun run db:deploy

WORKDIR /app/apps/cosketch-backend
RUN bun run build

EXPOSE 9000

CMD ["bun", "run", "start:backend"]
