FROM node:18-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./apps/http-backend ./apps/http-backend

RUN npm ci

WORKDIR /usr/src/app/apps/http-backend

RUN npm run db:generate
RUN npm run build

EXPOSE 9000

CMD ["npm", "run", "start:backend"]
