FROM oven/bun:1 AS base

WORKDIR /usr/src/app

COPY . .
RUN bun install

WORKDIR /usr/src/apps/packages/database
RUN bun run db:deploy

WORKDIR /usr/src/app/apps/cosketch-backend
RUN bun run build

EXPOSE 9000

CMD ["bun", "run", "start:backend"]
