name: Sketch.io frontend

on:
  push:
    branches: [production]
    paths:
      - "apps/Sketch.io-frontend/**"
      - "packages/**"
      - ".github/workflows/cd_frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code frontend
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/frontend.prod.Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
            NEXT_PUBLIC_HTTP_URL=${{ secrets.NEXT_PUBLIC_HTTP_URL }}
            NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL }}
          tags: |
            mohdyaqoob/Sketch.io-frontend:${{ github.sha }} 
            mohdyaqoob/Sketch.io-frontend:latest

#       - name: Deploy to VM
#         uses: appleboy/ssh-action@v1.2.0
#         with:
#           host: "${{secrets.HOST_IP}}"
#           username: "ubuntu"
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: 22
#           script: |
#             sudo docker pull mohdyaqoob/Sketch.io-frontend:latest

#             if sudo docker ps -a --format '{{.Names}}' | grep -q "^Sketch.io-frontend$"; then
#               sudo docker stop Sketch.io-frontend
#               sudo docker rm Sketch.io-frontend
#             fi

#             sudo docker run -d \
#               --name Sketch.io-frontend \
#               -p 3000:3000 \
#               --restart always \
#               mohdyaqoob/Sketch.io-frontend:latest

#             echo "Sketch.io frontend deployed successfully!"
#             sudo docker image prune -f --filter "until=24h"
